### ISSUE TITLE
Checking for broken links

### ISSUE THREAD

**Issue by vedantpuri** [vedantpuri/pyosphere#1]
## Expected Behavior
Symbolically linked file should be removed from execution environment if the user deletes it.

## Current Behavior
No such mechanism to delete the sym-link file

## Possible Solution
Check output of readlink -n of the file

## Steps to Reproduce
1. Create file
2. Create sym link of the file
3. Delete original file
4. Try accessing sym-linked file [Exists but can't be accessed]. This file should no longer exist

## Possible Implementation
Keep track of readlink -n output. Before Executing delete all broken links

[**Useful Resource**](https://stackoverflow.com/questions/22097130/delete-all-broken-symbolic-links-with-a-line)

**Comment by mayankk2308** [comment]
Invalid as we now use hard links with pruning.
